language: php
sudo: required
dist: trusty
group: edge
php:
 - hhvm
 - hhvm-nightly
 - hhvm-3.15
install: composer install
script:
 - hh_client
 - hhvm vendor/bin/phpunit
notifications:
  webhooks: https://code.facebook.com/travis/webhook/
